Regen after rev 123.
git-svn-id: http://svn.open64.net/svnroot/open64@124 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/projects/autoconf/configure b/projects/autoconf/configure
--- a/projects/autoconf/configure
+++ b/projects/autoconf/configure
@@ -273,7 +273,7 @@ PACKAGE_VERSION='2.0'
 PACKAGE_STRING='The Open64 compiler suite 2.0'
 PACKAGE_BUGREPORT='The Open64 Project'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB ALLOCA CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB ALLOCA CPP EGREP TARG_SUBDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4145,6 +4145,32 @@ _ACEOF
 
 fi
 
+
+case $target_cpu in
+    amd64|x86_64)
+
+cat >>confdefs.h <<\_ACEOF
+#define TARG_X8664 1
+_ACEOF
+
+	TARG_SUBDIR=x8664
+	;;
+    ia64)
+
+cat >>confdefs.h <<\_ACEOF
+#define TARG_IA64 1
+_ACEOF
+
+	TARG_SUBDIR=ia64
+	;;
+    *)
+	{ { echo "$as_me:$LINENO: error: *** Unsupported target architecture: $target_cpu" >&5
+echo "$as_me: error: *** Unsupported target architecture: $target_cpu" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+esac
+
+
                               ac_config_files="$ac_config_files Makefile kpro64/Makefile kpro64/targ_info/Makefile"
 
 cat >confcache <<\_ACEOF
@@ -4854,6 +4880,7 @@ s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@TARG_SUBDIR@,$TARG_SUBDIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
