- Added configure option:   --with-build-lib-optimize=DEFAULT|DEBUG
  Note that --with-build-optimize=DEBUG will now only enable debugging
  in the compiler build.

  The --help comment for --with-build-lib-optimize, notes
  that --with-build-lib-optimize=DEBUG is not well tested.

  Note that with this change compiler/library builds configured with
  --with-build-lib-optimize=DEBUG can now be used for performance
  testing.
- Breakup install rule into two rules, one for the GNU
  FEs (slow) and one for the compiler (fast), thus
  rebuilding and installing a component of the compiler
  can done via:

  make && make -C ../../.. install_compiler

  instead of:

  make && make -C ../../.. install

Reviewed by Steve Ellcey, approved by Jian-Xin Lai.


git-svn-id: http://svn.open64.net/svnroot/open64@3358 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 GCC_CONFIGURE_TARG GCC_DIR LIBLIST subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 GCC_CONFIGURE_TARG GCC_DIR LIBLIST subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -792,7 +792,9 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-build-compiler=GNU|OSP	Use GNU or OSP compilers in build
-  --with-build-optimize=DEFAULT|DEBUG	Use DEFAULT or DEBUG flags in build
+  --with-build-optimize=DEFAULT|DEBUG	Use DEFAULT or DEBUG flags in compiler build
+  --with-build-lib-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in library build.
+    Note that --with-build-lib-optimize=DEBUG is currently not well tested.
 
 _ACEOF
 fi
@@ -1416,6 +1418,29 @@ echo "$as_me: error: \"BUILD_OPTIMIZE=$BUILD_OPTIMIZE is not supported\"" >&2;}
     ;;
 esac
 
+
+# Check whether --with-build-lib-optimize or --without-build-lib-optimize was given.
+if test "${with_build_lib_optimize+set}" = set; then
+  withval="$with_build_lib_optimize"
+  BUILD_LIB_OPTIMIZE="$with_build_lib_optimize"
+else
+  BUILD_LIB_OPTIMIZE=DEFAULT
+fi;
+
+case "$BUILD_LIB_OPTIMIZE" in
+  DEFAULT|default)
+    BUILD_LIB_OPTIMIZE=DEFAULT
+    ;;
+  DEBUG|debug)
+    BUILD_LIB_OPTIMIZE=DEBUG
+    ;;
+  *)
+    { { echo "$as_me:$LINENO: error: \"BUILD_LIB_OPTIMIZE=$BUILD_LIB_OPTIMIZE is not supported\"" >&5
+echo "$as_me: error: \"BUILD_LIB_OPTIMIZE=$BUILD_LIB_OPTIMIZE is not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
+esac
+
 # BUILD_MULTILIB supports building libraries twice, this is used on x86
 # targets to have 32 and 64 bit libraries available.
 BUILD_MULTILIB=NO
@@ -1594,6 +1619,7 @@ export GCC_CONFIGURE_TARG
 export GCC_CONFIGURE_CFLAGS
 
 # Variables to replace in the configurable files.
+
 
 
 
@@ -2389,6 +2415,7 @@ s,@BUILD_HOST@,$BUILD_HOST,;t t
 s,@BUILD_TARGET@,$BUILD_TARGET,;t t
 s,@BUILD_VENDOR@,$BUILD_VENDOR,;t t
 s,@BUILD_OPTIMIZE@,$BUILD_OPTIMIZE,;t t
+s,@BUILD_LIB_OPTIMIZE@,$BUILD_LIB_OPTIMIZE,;t t
 s,@BUILD_COMPILER@,$BUILD_COMPILER,;t t
 s,@BUILD_BOTH@,$BUILD_BOTH,;t t
 s,@LIB_MACHINE_TYPE@,$LIB_MACHINE_TYPE,;t t
